///////////////////////////////////////////////////////////////////////////////
// 文件名：ImpactLogics.h
// 功能说明：所有效果头文件的总合
//
// 修改记录：
//
//
//
///////////////////////////////////////////////////////////////////////////////

#ifndef IMPACTLOGICS_H
#define IMPACTLOGICS_H

#include "ImpactLogic.h"
/*
#include "DI_AttackMe.h"
#include "DI_Damage.h"
#include "DI_Damages.h"
#include "DI_Heal.h"
#include "DI_HealPet.h"
#include "DI_JustSpecialEffect.h"
#include "DI_ModifyRage.h"
#include "DI_Teleport.h"

#include "IOT_Damage.h"
#include "IOT_Heal.h"

#include "DS_Absorb.h"
#include "DS_EMei009.h"
#include "DS_Emei014.h"
#include "DS_Ignore.h"
#include "DS_Reflect.h"
#include "DS_PetTrait.h"
#include "DS_PetDefence.h"
#include "DS_PetRevenge.h"
#include "DS_TransDamageToPet.h"
#include "DS_CounteractCriticalHit.h"
#include "DS_FilterDebuff.h"

#include "SOT_DamageMore.h"
#include "SOT_Faint.h"
#include "SOT_Root.h"
#include "SOT_PhyAttackImprove.h"
#include "SOT_DefenceAll.h"
#include "SOT_ResistAll.h"
#include "SOT_ShaoLin007.h"
#include "SOT_ShaoLin009.h"
#include "SOT_ShaoLin013.h"
#include "SOT_ShaoLin016.h"
#include "SOT_MoveSpeedRefix.h"
#include "SOT_MingJiao006.h"
#include "SOT_MingJiao008.h"
#include "SOT_MingJiao013.h"
#include "SOT_MingJiao015.h"
#include "SOT_AttrLevelOneAll.h"
#include "SOT_OtherAttrs.h"
#include "SOT_Terror.h"
#include "SOT_HpMpRageMax.h"
#include "SOT_JustSpecialEffect.h"
#include "SOT_Transform.h"
#include "SOT_HorseRide.h"
#include "SOT_StrikePointMax.h"
#include "SOT_GaiBang007.h"
#include "SOT_SelfResurrection.h"
#include "SOT_GaiBang012.h"
#include "SOT_ProlongSpecificImpact.h"
#include "SOT_XingXiu011.h"
#include "SOT_XingXiu017.h"
#include "SOT_Dali007.h"
#include "SOT_DaLi008.h"
#include "SOT_Dali012.h"
#include "SOT_DaLi015.h"
#include "SOT_Silence.h"
#include "SOT_Stealth.h"
#include "SOT_ShadowGuard.h"
#include "SOT_BodyEnhance.h"
#include "SOT_HitMissAndCriticalRefix.h"
#include "SOT_TianShan017.h"
#include "SOT_XiaoYaoTraps.h"
#include "SOT_PetAttr2Refix.h"
#include "SOT_Unbreakable.h"
#include "SOT_Emei016.h"
#include "SOT_DetectTrap.h"
#include "SOT_XiaoYao011.h"
#include "SOT_XiaoYao014.h"
#include "DS_WuDang006.h"
#include "DS_WuDang010.h"
#include "DS_WuDang014.h"
#include "SOT_WuDang016.h"
*/
#include "StdImpact000.h"
#include "StdImpact001.h"
#include "StdImpact002.h"
#include "StdImpact003.h"
#include "StdImpact004.h"
#include "StdImpact005.h"
#include "StdImpact006.h"
#include "StdImpact007.h"
#include "StdImpact008.h"
#include "StdImpact009.h"
#include "StdImpact010.h"
#include "StdImpact011.h"
#include "StdImpact012.h"
#include "StdImpact013.h"
#include "StdImpact014.h"
#include "StdImpact015.h"
#include "StdImpact016.h"
#include "StdImpact017.h"
#include "StdImpact018.h"
#include "StdImpact019.h"
#include "StdImpact020.h"
#include "StdImpact021.h"
#include "StdImpact022.h"
#include "StdImpact023.h"
#include "StdImpact024.h"
#include "StdImpact025.h"
#include "StdImpact026.h"
#include "StdImpact027.h"
#include "StdImpact028.h"
#include "StdImpact029.h"
#include "StdImpact030.h"
#include "StdImpact031.h"
#include "StdImpact032.h"
#include "StdImpact033.h"
#include "StdImpact034.h"
#include "StdImpact035.h"
#include "StdImpact036.h"
#include "StdImpact037.h"
#include "StdImpact038.h"
#include "StdImpact039.h"
#include "StdImpact040.h"
#include "StdImpact041.h"
#include "StdImpact042.h"
#include "StdImpact043.h"
#include "StdImpact044.h"
#include "StdImpact045.h"
#include "StdImpact046.h"
#include "StdImpact047.h"
#include "StdImpact048.h"
#include "StdImpact049.h"
#include "StdImpact050.h"
#include "StdImpact051.h"
#include "StdImpact052.h"
#include "StdImpact053.h"
#include "StdImpact054.h"
#include "StdImpact055.h"
#include "StdImpact056.h"
#include "StdImpact057.h"
/*
#include "StdImpact058.h"
#include "StdImpact059.h"
#include "StdImpact060.h"
#include "StdImpact061.h"
#include "StdImpact062.h"
#include "StdImpact063.h"
#include "StdImpact064.h"
#include "StdImpact065.h"
#include "StdImpact066.h"
#include "StdImpact067.h"
#include "StdImpact068.h"
#include "StdImpact069.h"
#include "StdImpact070.h"
#include "StdImpact071.h"
#include "StdImpact072.h"
#include "StdImpact073.h"
#include "StdImpact074.h"
#include "StdImpact075.h"
#include "StdImpact076.h"
#include "StdImpact077.h"
#include "StdImpact078.h"
#include "StdImpact079.h"

*/
namespace Combat_Module
{
	namespace Impact_Module
	{
	};
};
#endif //IMPACTLOGICS_H

