
"AddDispatchMissionInfoNM",LuaFnAddDispatchMissionInfoNM
"AddDyTitle",LuaFnAddDyTitle
"AddExp",LuaFnAddExp
"AddGlobalCountNews",LuaFnAddGlobalCountNews
"AddGPOwner",LuaFnAddGPOwner
"AddItem",LuaFnAddItem
"AddItemBonus",LuaFnAddItemBonus
"AddItemDemand",LuaFnAddItemDemand
"AddItemListToHuman",LuaFnAddItemListToHuman
"AddItemToBox",LuaFnAddItemToBox
"AddMission",LuaFnAddMission
"AddMissionEx",LuaFnAddMissionEx
"AddMissionNM",LuaFnAddMissionNM
"AddMissionTextNM",LuaFnAddMissionTextNM
"AddMoney",LuaFnAddMoney
"AddMoneyBonus",LuaFnAddMoneyBonus
"AddMonsterDropItem",LuaFnAddMonsterDropItem
"AddNumber",LuaFnAddNumber
"AddEventList""AddNumText",LuaFnAddNumText
"AddRadioItemBonus",LuaFnAddRadioItemBonus
"AddRandItemBonus",LuaFnAddRandItemBonus
"AddSkill",LuaFnAddSkill
"AddStorePointOnScene",LuaFnAddStorePointOnScene
"AddText",LuaFnAddText
"AddXinFa",LuaFnAddXinFa
"ApplyPlayerShop",LuaFnApplyPlayerShop
"AwardBangpaiTitle",LuaFnAwardBangPaiTitle
"AwardJieBaiTitle",LuaFnAwardJieBaiTitle
"AwardNickTitle",LuaFnAwardNickTitle
"AwardShangDianTitle",LuaFnAwardShangDianTitle
"AwardShiTuTitle",LuaFnAwardShiTuTitle
"AwardSpouseTitle",LuaFnAwardSpouseTitle
"AwardTitle",LuaFnAwardTitle
"BankBegin",LuaFnBankBegin
"BeginAddItem",LuaFnBeginAddItem
"BeginEvent",LuaFnBeginEvent
"BeginUICommand",LuaFnBeginUICommand
"CalcPetDomesticationMoney",LuaFnCalcPetDomesticationMoney
"CallScriptFunction",LuaFnCallScriptFunction
"CancelPetPlacard",LuaFnCancelPetPlacard
"CheckTimer",LuaFnCheckTimer
"CityBuildingChange",LuaFnCityBuildingChange
"CityCreate",LuaFnCityCreate
"CityDelete",LuaFnCityDelete
"CityGetCityList",LuaFnCityGetCityList
"CityMoveTo",LuaFnCityMoveTo
"ClearFollowedMembers",LuaFnClearFollowedMembers
"CostMoney",LuaFnCostMoney
"CreateMonsterOnScene",LuaFnCreateMonsterOnScene
"DeleteTitle",LuaFnDeleteTitle
"DelGPOwner",LuaFnDelGPOwner
"DelItem",LuaFnDelItem
"DelMission",LuaFnDelMission
"DelMissionNM",LuaFnDelMissionNM
"DelSkill",LuaFnDelSkill
"DelStorePointOnScene",LuaFnDelStorePointOnScene
"DelXinFa",LuaFnDelXinFa
"DestroyMenPai",LuaFnDestroyMenPai
"DispatchAbilityInfo",LuaFnDispatchAbilityInfo
"DispatchAllTitle",LuaFnDispatchAllTitle
"DispatchEventList",LuaFnDispatchEventList
"DispatchMenpaiInfo",LuaFnDispatchMenpaiInfo
"DispatchMissionContinueInfo",LuaFnDispatchMissionContinueInfo
"DispatchMissionDemandInfo",LuaFnDispatchMissionDemandInfo
"DispatchMissionInfo",LuaFnDispatchMissionInfo
"DispatchMissionResult",LuaFnDispatchMissionResult
"DispatchMissionTips",LuaFnDispatchMissionTips
"DispatchPetPlacardList",LuaFnDispatchPetPlacardList
"DispatchPlayerShopList",LuaFnDispatchPlayerShopList
"DispatchPlayerShopSaleOutList",LuaFnDispatchPlayerShopSaleOutList
"DispatchRegieEventList",LuaFnDispatchRegieEventList
"DispatchShopItem",LuaFnDispatchShopItem
"DispatchUICommand",LuaFnDispatchUICommand
"DispatchXinfaLevelInfo",LuaFnDispatchXinfaLevelInfo
"EnableBankRentIndex",LuaFnEnableBankRentIndex
"EnableItemBoxPickOwnerTime",LuaFnEnableItemBoxPickOwnerTime
"EndAddItem",LuaFnEndAddItem
"EndEvent",LuaFnEndEvent
"EndUICommand",LuaFnEndUICommand
"EraseItem",LuaFnEraseItem
"FindStorePointOnScene",LuaFnFindStorePointOnScene
"FinishKillObjGetItem",LuaFnFinishKillObjGetItem
"GetAbilityExp",LuaFnGetAbilityExp
"GetAbilityExpPlus",LuaFnGetAbilityExpPlus
"GetAbilityObjIndex",LuaFnGetAbilityObjIndex
"GetAbilityOperaRobotTime",LuaFnGetAbilityOperaRobotTime
"GetBagItemDur",LuaFnGetBagItemDur
"GetBagItemIdent",LuaFnGetBagItemIdent
"GetBagItemParam",LuaFnGetBagItemParam
"GetBankRentIndex",LuaFnGetBankRentIndex
"GetCon",LuaFnGetCon
"GetCurCamp",LuaFnGetCurCamp
"GetDist",LuaFnGetDist
"GetDyTitlesNum",LuaFnGetDyTitlesNum
"GetExp",LuaFnGetExp
"GetFollowedMember",LuaFnGetFollowedMember
"GetFollowedMembersCount",LuaFnGetFollowedMembersCount
"GetGameTime",LuaFnGetGameTime
"GetGemEmbededCount",LuaFnGetGemEmbededCount
"GetGPCountByOwner",LuaFnGetGPCountByOwner
"GetHp",LuaFnGetHp
"GetHumanEnergy",LuaFnGetHumanEnergy
"GetHumanEnergyRegeneRate",LuaFnGetHumanEnergyRegeneRate
"GetHumanGUID",LuaFnGetHumanGUID
"GetHumanHairColor",LuaFnGetHumanHairColor
"GetHumanHairModel",LuaFnGetHumanHairModel
"GetHumanMaxEnergy",LuaFnGetHumanMaxEnergy
"GetHumanMaxVigor",LuaFnGetHumanMaxVigor
"GetHumanVigor",LuaFnGetHumanVigor
"GetHumanVigorRegeneRate",LuaFnGetHumanVigorRegeneRate
"GetHumanWorldX",LuaFnGetHumanWorldX
"GetHumanWorldZ",LuaFnGetHumanWorldZ
"GetItemBoxMaxGrowTime",LuaFnGetItemBoxMaxGrowTime
"GetItemBoxOpenFlag",LuaFnGetItemBoxOpenFlag
"GetItemBoxOwner",LuaFnGetItemBoxOwner
"GetItemBoxRecycleTimes",LuaFnGetItemBoxRecycleTimes
"GetItemBoxRequireAbilityID",LuaFnGetItemBoxRequireAbilityID
"GetItemBoxWorldPosX",LuaFnGetItemBoxWorldPosX
"GetItemBoxWorldPosZ",LuaFnGetItemBoxWorldPosZ
"GetItemCount",LuaFnGetItemCount
"GetItemIndex",LuaFnGetItemIndex
"GetItemQuality",LuaFnGetItemQuality
"GetItemTableIndexByIndex",LuaFnGetItemTableIndexByIndex
"GetLevel",LuaFnGetLevel
"GetMenPai",LuaFnGetMenPai
"GetMenPaiFigure",LuaFnGetMenPaiFigure
"GetMenPaiMaster",LuaFnGetMenPaiMaster
"GetMenPaiTitle",LuaFnGetMenPaiTitle
"GetMission",LuaFnGetMission
"GetMissionCount",LuaFnGetMissionCount
"GetMissionData",LuaFnGetMissionData
"GetMissionDataBit",LuaFnGetMissionDataBit
"GetMissionIndexByID",LuaFnGetMissionIndexByID
"GetMissionIndexByIDNM",LuaFnGetMissionIndexByIDNM
"GetMissionItemNM",LuaFnGetMissionItemNM
"GetMissionParam",LuaFnGetMissionParam
"GetMissionTypeNM",LuaFnGetMissionTypeNM
"GetMoney",LuaFnGetMoney
"GetMonsterCount",LuaFnGetMonsterCount
"GetMonsterDataID",LuaFnGetMonsterDataID
"GetMonsterGroupID",LuaFnGetMonsterGroupID
"GetMonsterObjID",LuaFnGetMonsterObjID
"GetMonsterOwnerCount",LuaFnGetMonsterOwnerCount
"GetMonsterOwnerID",LuaFnGetMonsterOwnerID
"GetMonsterTeamID",LuaFnGetMonsterTeamID
"GetMonsterWayInfoNM",LuaFnGetMonsterWayInfoNM
"GetMp",LuaFnGetMp
"GetName",LuaFnGetName
"GetNearTeamCount",LuaFnGetNearTeamCount
"GetNearTeamMember",LuaFnGetNearTeamMember
"GetNeedItemNumNM",LuaFnGetNeedItemNumNM
"GetNeedKillObjNumNM",LuaFnGetNeedKillObjNumNM
"GetNumText""GetEventList",LuaFnGetNumText
"GetQuestionsRecord",LuaFnGetQuestionsRecord
"GetSex",LuaFnGetSex
"GetStoreMapSceneID",LuaFnGetStoreMapSceneID
"GetStoreMapX",LuaFnGetStoreMapX
"GetStoreMapZ",LuaFnGetStoreMapZ
"GetStorePointType",LuaFnGetStorePointType
"GetTeamId",LuaFnGetTeamId
"GetTeamMemberGuid",LuaFnGetTeamMemberGuid
"GetTeamSceneMemberCount",LuaFnGetTeamSceneMemberCount
"GetTeamSize",LuaFnGetTeamSize
"GetTitle",LuaFnGetTitle
"GetWorldPos",LuaFnGetWorldPos
"GuildCreate",LuaFnGuildCreate
"GuildList",LuaFnGuildList
"HaveItem",LuaFnHaveItem
"HaveItemInBag",LuaFnHaveItemInBag
"HaveSkill",LuaFnHaveSkill
"HaveXinFa",LuaFnHaveXinFa
"IfFinishdKillObjNM",LuaFnIfFinishdKillObjNM
"IsCanEnterCopyScene",LuaFnIsCanEnterCopyScene
"IsCaptain",LuaFnIsCaptain
"IsHaveMission",LuaFnIsHaveMission
"IsHaveMissionNM",LuaFnIsHaveMissionNM
"IsInDist",LuaFnIsInDist
"IsMissionHaveDone",LuaFnIsMissionHaveDone
"IsMissionHaveDoneNM",LuaFnIsMissionHaveDoneNM
"IsPrescrLearned",LuaFnIsPrescrLearned
"IssuePetPlacard",LuaFnIssuePetPlacard
"IssuePetPlacardByIndex",LuaFnIssuePetPlacardByIndex
"IsTeamFollow",LuaFnIsTeamFollow
"ItemBoxEnterScene",LuaFnItemBoxEnterScene
"LeaveTeam",LuaFnLeaveTeam
"ListMissionsNM",LuaFnListMissionsNM
"MisMsg2PlayerNM",LuaFnMisMsg2PlayerNM
"MissionCheckAcceptNM",LuaFnMissionCheckAcceptNM
"MissionCheckSubmitNM",LuaFnMissionCheckSubmitNM
"MissionCom",LuaFnMissionCom
"MissionComplateInfoNM",LuaFnMissionComplateInfoNM
"MissionComplateNM",LuaFnMissionComplateNM
"MissionNotComplateInfoNM",LuaFnMissionNotComplateInfoNM
"Msg2Player",LuaFnMsg2Player
"Msg2Team",LuaFnMsg2Team
"NewWorld",LuaFnNewWorld
"OnMissionAcceptNM",LuaFnOnMissionAcceptNM
"PetDomestication",LuaFnPetDomestication
"PetStudySkill",LuaFnPetStudySkill
"PetStudySkill_MenPai",LuaFnPetStudySkill_MenPai
"PrintNum",LuaFnPrintNum
"PrintStr",LuaFnPrintStr
"QueryAreaStandingTime",LuaFnQueryAreaStandingTime
"QueryHumanAbility",LuaFnQueryHumanAbility
"QueryHumanAbilityLevel",LuaFnQueryHumanAbilityLevel
"RemoveMonster",LuaFnRemoveMonster
"RequestMissionNM",LuaFnRequestMissionNM
"ResetAreaStandingTime",LuaFnResetAreaStandingTime
"RestoreHp",LuaFnRestoreHp
"RestoreMp",LuaFnRestoreMp
"RestoreNpcCamp",LuaFnRestoreNpcCamp
"SetAbilityExp",LuaFnSetAbilityExp
"SetAbilityOperaRobotTime",LuaFnSetAbilityOperaRobotTime
"SetAbilityOperaTime",LuaFnSetAbilityOperaTime
"SetBagItemDur",LuaFnSetBagItemDur
"SetBagItemIdent",LuaFnSetBagItemIdent
"SetBagItemParam",LuaFnSetBagItemParam
"SetCurCamp",LuaFnSetCurCamp
"SetHumanAbilityLevel",LuaFnSetHumanAbilityLevel
"SetHumanEnergy",LuaFnSetHumanEnergy
"SetHumanEnergyRegeneRate",LuaFnSetHumanEnergyRegeneRate
"SetHumanHairColor",LuaFnSetHumanHairColor
"SetHumanHairModel",LuaFnSetHumanHairModel
"SetHumanMaxEnergy",LuaFnSetHumanMaxEnergy
"SetHumanMaxVigor",LuaFnSetHumanMaxVigor
"SetHumanVigor",LuaFnSetHumanVigor
"SetHumanVigorRegeneRate",LuaFnSetHumanVigorRegeneRate
"SetItemBoxMaxGrowTime",LuaFnSetItemBoxMaxGrowTime
"SetItemBoxOwner",LuaFnSetItemBoxOwner
"SetItemBoxPickOwnerTime",LuaFnSetItemBoxPickOwnerTime
"SetItemBoxRecycleTimes",LuaFnSetItemBoxRecycleTimes
"SetLevel",LuaFnSetLevel
"SetMenPai",LuaFnSetMenPai
"SetMissionByIndex",LuaFnSetMissionByIndex
"SetMissionData",LuaFnSetMissionData
"SetMissionDataBit",LuaFnSetMissionDataBit
"SetMissionEvent",LuaFnSetMissionEvent
"SetNpcCurCamp",LuaFnSetNpcCurCamp
"SetPatrolId",LuaFnSetPatrolId
"SetPos",LuaFnSetPos
"SetPrescription",LuaFnSetPrescription
"SetRevPos",LuaFnSetRevPos
"SetTeamFollowSpeed",LuaFnSetTeamFollowSpeed
"SetTimer",LuaFnSetTimer
"StopTeamFollow",LuaFnStopTeamFollow
"StopTimer",LuaFnStopTimer
"SubmitMissionNM",LuaFnSubmitMissionNM
"TryRecieveItem",LuaFnTryRecieveItem
"UICommand_AddInt",LuaFnUICommand_AddInt
"UICommand_AddString",LuaFnUICommand_AddString
"UseSkill",LuaFnUseSkill
"GetDayTime",LuaGetDayTime
"GetObjCreateTime",LuaGetObjCreateTime
"SetPlayerDefaultReliveInfo",LuaSetPlayerDefaultReliveInfo