// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "explorer_helper.h"

/////////////////////////////////////////////////////////////////////////////
// CExplorer_help

IMPLEMENT_DYNCREATE(CExplorer_help, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CExplorer_help properties

/////////////////////////////////////////////////////////////////////////////
// CExplorer_help operations
