//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: ActorAnimationSetting.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_ActorAnimationSetting_H__
#define __WDR_ActorAnimationSetting_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "ActorAnimationSetting_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT = 10000;
const int ID_LISTBOX_ANIMATION = 10001;
const int ID_BUTTON_PLAY = 10002;
const int ID_BUTTON_STOP = 10003;
const int ID_BUTTON_STEP_BACK = 10004;
const int ID_BUTTON_STEP_FRONT = 10005;
const int ID_CHECKBOX_LOOP = 10006;
const int ID_LISTBOX_ALL_SKILL = 10007;
const int ID_BUTTON_ADD_SKILL = 10008;
const int ID_BUTTON_DEL_SKILL = 10009;
const int ID_BUTTON_SET_SKILL = 10010;
const int ID_BUTTON_LEFTWEAPON = 10011;
const int ID_BUTTON_RIGTHTWEAPON = 10012;
const int ID_BUTTON_MOUNT = 10013;
const int ID_TEXTCTRL_HAIR = 10014;
const int ID_TEXTCTRL_HAIR_MAT = 10015;
const int ID_TEXTCTRL_CAP = 10016;
const int ID_TEXTCTRL_CAP_MAT = 10017;
const int ID_TEXTCTRL_BODY = 10018;
const int ID_TEXTCTRL_BODY_MAT = 10019;
const int ID_TEXTCTRL_HAND = 10020;
const int ID_TEXTCTRL_HAND_MAT = 10021;
const int ID_TEXTCTRL_FOOT = 10022;
const int ID_TEXTCTRL_FOOT_MAT = 10023;
const int ID_BUTTON_COLOUR = 10024;
const int ID_BUTTON_CLOTH = 10025;
const int ID_SLIDER_TIME = 10026;
const int ID_SLIDER_GLOBAL_ANIM_RATE = 10027;
const int ID_SLIDER_FADE_OUT_TIME = 10028;
wxSizer *ActorAnimationSetting( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

wxBitmap AnimationSettingBitmap( size_t index );

#endif

// End of generated file
