//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: AutoSaveSetting.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_AutoSaveSetting_H__
#define __WDR_AutoSaveSetting_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "AutoSaveSetting_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_CHECKBOX_AUTO_SAVE = 10000;
const int ID_TEXT = 10001;
const int ID_TEXTCTRL_AUTO_SAVE_INTERVAL = 10002;
wxSizer *AutoSaveSetting( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
