//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: BrushSelector.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_BrushSelector_H__
#define __WDR_BrushSelector_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "BrushSelector_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int feID_RELOAD_PIXMAP_LIST = 10000;
const int feID_PIXMAP_LIST = 10001;
const int feID_PIXMAP_PREVIEW = 10002;
const int feID_ENABLE_PIXMAP_PREVIEW = 10003;
const int feID_FLIP_HORIZONTAL = 10004;
const int feID_FLIP_VERTICAL = 10005;
const int feID_ROTATE_RIGHT_ANGLE = 10006;
const int feID_MIRROR_DIAGONAL = 10007;
const int feID_RANDOM = 10008;
const int feID_PIXMAP_FULLTERRAINPAINT = 10008;
const int feID_PIXMAP_PAINTINONEGRID = 10009;
const int feID_PIXMAP_REPLACE = 10010;

wxSizer *InitPixmapSelector( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

wxBitmap CellGridBitmaps( size_t index );

#endif

// End of generated file
