//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: CameraTrackSetting.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_CameraTrackSetting_H__
#define __WDR_CameraTrackSetting_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "CameraTrackSetting_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT = 10000;
const int ID_LISTBOX_CAMERA_INFO = 10001;
const int ID_TEXTCTRL_CODE = 10002;
const int ID_BUTTON_SAVE = 10003;
const int ID_BUTTON_LOAD = 10004;
const int ID_TEXTCTRL_TRACK_LENGTH = 10005;
const int ID_TEXTCTRL_POINT_TIME = 10006;
const int ID_BUTTON_ADDPOINT = 10007;
const int ID_SPINCTRL_MODIFY_POINT = 10008;
const int ID_BUTTON_MODIFY = 10009;
const int ID_BUTTON_PLAY = 10010;
const int ID_BUTTON_STOP = 10011;
const int ID_BUTTON_CLEAR = 10012;
const int ID_TEXTCTRL_POINT_INDEX = 10013;
const int ID_TEXTCTRL_POSITION = 10014;
const int ID_TEXTCTRL_ROTATION = 10015;
const int ID_TEXTCTRL_TIME = 10016;
const int ID_BUTTON_MODIFY_MANUAL = 10017;
const int ID_BUTTON_REMOVE_POINT = 10018;
const int ID_TEXT_CURR_CAMERA_POS = 10019;
wxSizer *InitCameraTrackSetting( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
