//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: ChangeMonsgerInfo.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_ChangeMonsgerInfo_H__
#define __WDR_ChangeMonsgerInfo_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "ChangeMonsgerInfo_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT1 = 10000;
const int ID_TEXTCTRL_REFRESH_TIME1 = 10001;
const int ID_TEXTCTRL_AREA_RADIUS1 = 10002;
const int ID_BUTTON_CHANGE_TIME = 10003;
const int ID_BUTTON_CHANGE_RADIUS = 10004;
const int ID_BUTTON_CHANGE_BOTH = 10005;
const int ID_BUTTON_CANCEL = 10006;
wxSizer *ChangeMonsterInfo( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
