//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: ClothSetting.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_ClothSetting_H__
#define __WDR_ClothSetting_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "ClothSetting_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT = 10000;
const int ID_TEXTCTRL_WIDTH = 10001;
const int ID_TEXTCTRL_HEIGHT = 10002;
const int ID_TEXTCTRL_MASS = 10003;
const int ID_TEXTCTRL_NATURALLENGTH = 10004;
const int ID_TEXTCTRL_STRUCTURALSTIFFNESS = 10005;
const int ID_TEXTCTRL_SHEARSTIFFNESS = 10006;
const int ID_TEXTCTRL_FLEXIONSTIFFNESS = 10007;
const int ID_TEXTCTRL_DEFORMATIONRATE = 10008;
const int ID_TEXTCTRL_WINDVELOCITY = 10009;
const int ID_TEXTCTRL_MATERIAL = 10010;
const int ID_TEXTCTRL_HEADPOINTNAME = 10011;
const int ID_TEXTCTRL_HEADPOINT = 10012;
const int ID_TEXTCTRL_TAILPOINTNAME = 10013;
const int ID_TEXTCTRL_TAILPOINT = 10014;
const int ID_BUTTON_ADD = 10015;
wxSizer *ClothSetting( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
