//------------------------------------------------------------------------------
// Source code generated by wxDesigner from file: ClothSetting.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma implementation "ClothSetting_wdr.h"
#endif

// For compilers that support precompilation
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// Include private header
#include "ClothSetting_wdr.h"

#include <wx/intl.h>

// Euro sign hack of the year
#if wxUSE_UNICODE
    #define __WDR_EURO__ wxT("\u20ac")
#else
    #if defined(__WXMAC__)
        #define __WDR_EURO__ wxT("\xdb")
    #elif defined(__WXMSW__)
        #define __WDR_EURO__ wxT("\x80")
    #else
        #define __WDR_EURO__ wxT("\xa4")
    #endif
#endif

// Implement window functions

wxSizer *ClothSetting( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 2, 0, 0 );

    wxStaticText *item1 = new wxStaticText( parent, ID_TEXT, _("width"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item2 = new wxTextCtrl( parent, ID_TEXTCTRL_WIDTH, _("10"), wxDefaultPosition, wxSize(80,-1), wxTE_PROCESS_ENTER );
    item0->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item3 = new wxStaticText( parent, ID_TEXT, _("height"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item4 = new wxTextCtrl( parent, ID_TEXTCTRL_HEIGHT, _("20"), wxDefaultPosition, wxSize(80,-1), wxTE_PROCESS_ENTER );
    item0->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item5 = new wxStaticText( parent, ID_TEXT, _("mass"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item6 = new wxTextCtrl( parent, ID_TEXTCTRL_MASS, _("0.0006"), wxDefaultPosition, wxSize(80,-1), wxTE_PROCESS_ENTER );
    item0->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item7 = new wxStaticText( parent, ID_TEXT, _("naturalLength"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item8 = new wxTextCtrl( parent, ID_TEXTCTRL_NATURALLENGTH, _("0.05"), wxDefaultPosition, wxSize(80,-1), wxTE_PROCESS_ENTER );
    item0->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item9 = new wxStaticText( parent, ID_TEXT, _("structuralStiffness"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item10 = new wxTextCtrl( parent, ID_TEXTCTRL_STRUCTURALSTIFFNESS, _("2"), wxDefaultPosition, wxSize(80,-1), wxTE_PROCESS_ENTER );
    item0->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item11 = new wxStaticText( parent, ID_TEXT, _("shearStiffness"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item12 = new wxTextCtrl( parent, ID_TEXTCTRL_SHEARSTIFFNESS, _("2"), wxDefaultPosition, wxSize(80,-1), wxTE_PROCESS_ENTER );
    item0->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item13 = new wxStaticText( parent, ID_TEXT, _("flexionStiffness"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item14 = new wxTextCtrl( parent, ID_TEXTCTRL_FLEXIONSTIFFNESS, _("1"), wxDefaultPosition, wxSize(80,-1), wxTE_PROCESS_ENTER );
    item0->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item15 = new wxStaticText( parent, ID_TEXT, _("deformationRate"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item16 = new wxTextCtrl( parent, ID_TEXTCTRL_DEFORMATIONRATE, _("0.1"), wxDefaultPosition, wxSize(80,-1), wxTE_PROCESS_ENTER );
    item0->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item17 = new wxStaticText( parent, ID_TEXT, _("windVelocity"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item18 = new wxTextCtrl( parent, ID_TEXTCTRL_WINDVELOCITY, _("0 0 100"), wxDefaultPosition, wxSize(80,-1), wxTE_PROCESS_ENTER );
    item0->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item19 = new wxStaticText( parent, ID_TEXT, _("material"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item20 = new wxTextCtrl( parent, ID_TEXTCTRL_MATERIAL, wxT(""), wxDefaultPosition, wxSize(120,-1), wxTE_PROCESS_ENTER );
    item0->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item21 = new wxStaticText( parent, ID_TEXT, _("head point name"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item21, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item22 = new wxTextCtrl( parent, ID_TEXTCTRL_HEADPOINTNAME, wxT(""), wxDefaultPosition, wxSize(120,-1), wxTE_PROCESS_ENTER );
    item0->Add( item22, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item23 = new wxStaticText( parent, ID_TEXT, _("head point"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item24 = new wxTextCtrl( parent, ID_TEXTCTRL_HEADPOINT, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_PROCESS_ENTER );
    item0->Add( item24, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item25 = new wxStaticText( parent, ID_TEXT, _("tail point name"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item25, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item26 = new wxTextCtrl( parent, ID_TEXTCTRL_TAILPOINTNAME, wxT(""), wxDefaultPosition, wxSize(120,-1), wxTE_PROCESS_ENTER );
    item0->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item27 = new wxStaticText( parent, ID_TEXT, _("tail point"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item27, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item28 = new wxTextCtrl( parent, ID_TEXTCTRL_TAILPOINT, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_PROCESS_ENTER );
    item0->Add( item28, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item29 = new wxButton( parent, ID_BUTTON_ADD, _("Add"), wxDefaultPosition, wxDefaultSize, 0 );
    item0->Add( item29, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

// Implement menubar functions

// Implement toolbar functions

// Implement bitmap functions


// End of generated file
