//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: DatuPointEditDlg.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_DatuPointEditDlg_H__
#define __WDR_DatuPointEditDlg_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "DatuPointEditDlg_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_LISTBOX_POINTS = 10000;
const int ID_TEXT = 10001;
const int ID_TEXTCTRL_RADIUS = 10002;
const int ID_TEXTCTRL_XPOS = 10003;
const int ID_TEXTCTRL_ZPOS = 10004;
const int ID_TEXTCTRL_DEFAULT_RADIUS = 10005;
const int ID_BUTTON_BEGIN_ADD_POINT = 10006;
const int ID_BUTTON_END_ADD_POINT = 10007;
const int ID_BUTTON_DELETE_POINT = 10008;
wxSizer *DatuPointEditDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
