//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: EraseTexDialog.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_EraseTexDialog_H__
#define __WDR_EraseTexDialog_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "EraseTexDialog_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT_TEX_NAME = 10000;
const int ID_COMBO_TEXNAME = 10001;
wxSizer *EraseTexName( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
