//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: ExceptionInfoList.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_ExceptionInfoList_H__
#define __WDR_ExceptionInfoList_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "ExceptionInfoList_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_EXCEPTION_LISTBOX = 10000;
const int ID_BUTTON_DELETE_FROM_SCENE = 10002;
const int ID_BUTTON_RELOCATE = 10003;

wxSizer *ExceptionInfo( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );
wxSizer *ExceptionHandle( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );


// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
