//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: GrowPointEdit.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_GrowPointEdit_H__
#define __WDR_GrowPointEdit_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "GrowPointEdit_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT_11 = 10000;
const int ID_LISTCTRL_GROW_POINT = 10001;
const int ID_TEXT_22 = 10002;
const int ID_TREECTRL_ADDED_GROW_POINT = 10003;
wxSizer *GrowPointDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
