//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: MaterialSetting.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_MaterialSetting_H__
#define __WDR_MaterialSetting_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "MaterialSetting_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_COMBO_MATERIAL = 10000;
const int ID_BUTTON_SELECT = 10001;
const int ID_TEXTCTRL_TEXTURE_NAME = 10002;
const int ID_BUTTON_OPEN = 10003;
const int ID_TEXT = 10004;
const int ID_BUTTON_EMISSIVE = 10005;
const int ID_TEXT_DURATION = 10006;
const int ID_TEXTCTRL_DURATION = 10007;
const int ID_TEXT_DRAW_STYLE = 10008;
const int ID_COMBO_DRAW_STYLE = 10009;
const int ID_COMBO_STAGE_STYLE = 10010;
const int ID_TEXT_TEX_ADD_MODE = 10011;
const int ID_COMBO_TEX_ADD_MODE = 10012;
const int ID_TEXT_TEX_SCALE = 10013;
const int ID_TEXTCTRL_SCALE = 10014;
const int ID_TEXTCTRL_ROTATE_ANIM = 10015;
const int ID_CHECKBOX_TWO_SIDE = 10016;
const int ID_BUTTON_SAVE = 10017;
wxSizer *MaterialSetting( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
