//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: MiniMapMaker.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_MiniMapMaker_H__
#define __WDR_MiniMapMaker_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "MiniMapMaker_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT = 10000;
const int ID_TEXTCTRL_FILE_NAME = 10001;
const int ID_TEXTCTRL_TILE_SIZE = 10002;
const int ID_TEXTCTRL_TILE_TEX_WIDTH = 10003;
const int ID_TEXTCTRL_TILE_TEX_HEIGHT = 10004;
const int ID_COMBO_TEX_EXTENSION = 10005;
const int ID_CHECKBOX_DEL_TEMP_FILES = 10006;
const int ID_COMBO_CAMERA_DIRECTION = 10007;
const int ID_BUTTON_CREATE_MINI_MAP = 10008;
wxSizer *MiniMapMaker( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
