//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: MonsterEdit.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_MonsterEdit_H__
#define __WDR_MonsterEdit_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "MonsterEdit_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_LISTCTRL_MOSTER_EDIT = 10000;
const int ID_TEXT = 10001;
const int ID_TEXTCTRL_MONSTER_NAME = 10002;
const int ID_TEXTCTRL_MONSTER_LEVEL = 10003;
const int ID_TEXTCTRL_MONSTER_MOVE_SPEED = 10004;
const int ID_TEXTCTRL_MONSTER_EXP = 10005;
const int ID_TEXTCTRL_MONSTER_REFRESH_TIME = 10006;
const int ID_TEXTCTRL_MONSTER_MVOE_RADIUS = 10007;
const int ID_TEXTCTRL_MONSTER_CAMP_ID = 10008;
const int ID_TEXTCTRL_MONSTER_REPUTATION_ID = 10009;
const int ID_LINE = 10010;
const int ID_CHOICE_BASE_AI = 10011;
const int ID_TEXTCTRL_MONSTER_BASE_AI_ID = 10012;
const int ID_CHOICE_AI_FILE = 10013;
const int ID_TEXTCTRL_AI_FILE = 10014;
const int ID_COMBO_EVEN_FILE = 10015;
const int ID_TEXTCTRL_EVEN_FILE = 10016;
const int ID_TEXTCTRL_GROUP_ID = 10017;
const int ID_TEXTCTRL_TEAM_ID = 10018;
const int ID_TEXT_INSTANCE_NAME = 10019;
const int ID_TEXTCTRL_INSTANCE_NAME = 10020;
const int ID_TEXT_GUID = 10021;
const int ID_TEXTCTRL_GUID = 10022;
const int ID_BUTTON_DIR_DEC = 10023;
const int ID_BUTTON_DIR_INC = 10024;
const int ID_TEXTCTRL_DIRECT = 10025;
const int ID_TEXT_PATROL = 10026;
const int ID_TEXTCTRL_PATROL = 10027;
const int ID_TEXT_MONSTER_EDIT_TITLE = 10028;
const int ID_TEXTCTRL_TITLE = 10029;
const int ID_BUTTON_MODIFY_MONSTER_INFO = 10030;
const int ID_TREECTRL_ADDED_MONSTER = 10031;
const int ID_TEXT_SHOP1 = 10032;
const int ID_CHOICE_SHOP1 = 10033;
const int ID_TEXT_SHOP2 = 10034;
const int ID_CHOICE_SHOP2 = 10035;
const int ID_TEXT_SHOP3 = 10036;
const int ID_CHOICE_SHOP3 = 10037;
const int ID_TEXT_SHOP4 = 10038;
const int ID_CHOICE_SHOP4 = 10039;
const int ID_CHOICE_TYPE = 10040;
wxSizer *MonsterEditDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
