//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: MountSetting.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_MountSetting_H__
#define __WDR_MountSetting_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "MountSetting_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT = 10000;
const int ID_TEXTCTRL_ATTACHED_MODEL_ONE = 10001;
const int ID_COMBO_LOCATOR1 = 10002;
const int ID_TEXTCTRL_OFFSET_POS1 = 10003;
const int ID_TEXTCTRL_ANIMATION1 = 10004;
const int ID_LINE = 10005;
const int ID_TEXTCTRL_ATTACHED_MODEL_TWO = 10006;
const int ID_COMBO_LOCATOR2 = 10007;
const int ID_TEXTCTRL_OFFSET_POS2 = 10008;
const int ID_TEXTCTRL_ANIMATION2 = 10009;
const int ID_COMBO_MOUNT_ANIM = 10010;
const int ID_BUTTON_RESET_ANIM = 10011;
wxSizer *MountSetting( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
