//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: NewScene.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_NewScene_H__
#define __WDR_NewScene_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "NewScene_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TILESIZETEXTCTRL = 10000;
const int ID_XSIZETEXTCTRL = 10001;
const int ID_ZSIZETEXTCTRL = 10002;
const int ID_SEEDTEXTCTRL = 10003;
const int ID_SCALETEXTCTRL = 10004;
const int ID_HEIGHTSCALECTRL = 10005;
const int ID_COMBO = 10006;
const int ID_CHOICE = 10007;
wxSizer *NewScene( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
