//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: NpcPatrolEdit.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_NpcPatrolEdit_H__
#define __WDR_NpcPatrolEdit_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "NpcPatrolEdit_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT = 10000;
const int ID_LISTBOX_LINE = 10001;
const int ID_LISTBOX_POINT = 10002;
const int ID_BN_ADD_NEW_LINE = 10003;
const int ID_BUTTON_DEL_LINE = 10004;
const int ID_BUTTON_LINE_OK = 10005;
const int ID_BUTTON_DEL_POINT = 10006;
const int ID_POINT_X = 10007;
const int ID_POINT_Y = 10008;
const int ID_IFY = 10009;
const int ID_POINT_Z = 10010;
const int ID_DISTANCE = 10011;
wxSizer *EditRegionDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
