//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: ParticleEditor.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_ParticleEditor_H__
#define __WDR_ParticleEditor_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "ParticleEditor_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_BUTTON_REFRESH = 10000;
const int ID_BUTTON_SAVE = 10001;
const int ID_BUTTON_ADD_EMITTER = 10002;
const int ID_COMBO_EMITTER = 10003;
const int ID_BUTTON_ADD_AFFECTOR = 10004;
const int ID_COMBO_AFFECTOR = 10005;
const int ID_CHECKBOX_INSERT = 10006;
const int ID_BUTTON_DELETE = 10007;
const int ID_PROPERTY_EDITOR = 10008;
const int ID_BUTTON_SHOW_MATERIAL_EDITOR = 10009;

wxSizer *ParticleEditor( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
