//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: RegionEdit.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_RegionEdit_H__
#define __WDR_RegionEdit_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "RegionEdit_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT = 10000;
const int ID_LISTBOX_REGION = 10001;
const int ID_LISTBOX_POINT = 10002;
const int ID_BN_ADD_NEW_REGION = 10003;
const int ID_BUTTON_DEL_REGION = 10004;
const int ID_BUTTON_REGION_OK = 10005;
const int ID_BUTTON_DEL_POINT = 10006;
const int ID_CHK_FLYABLE = 10007;
const int ID_LISTBOX_Line = 10008;
const int ID_CHOICE_LINE_PROPERTY = 10009;
wxSizer *EditRegion( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
