//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: SoundEditDlg.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_SoundEditDlg_H__
#define __WDR_SoundEditDlg_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "SoundEditDlg_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_LISTBOX_SCENE_SOUND = 10000;
const int ID_TEXT = 10001;
const int ID_TEXT_SOUNDIDTEXT = 10002;
const int ID_COMBO_SOUND_NAME = 10003;
const int ID_TEXTCTRL_RADIUS = 10004;
const int ID_TEXTCTRL_XPOS = 10005;
const int ID_TEXTCTRL_ZPOS = 10006;
const int ID_TEXTCTRL_REPEAT_TIME = 10007;
const int ID_TEXTCTRL_REPEAT_INTERVAL_TIME = 10008;
const int ID_TEXTCTRL_NEXT_REPEAT_TIME = 10009;
const int ID_BUTTON_BEGIN_ADD_SOUND = 10010;
const int ID_BUTTON_END_ADD_SOUND = 10011;
const int ID_BUTTON_DELETE_SOUND = 10012;
const int ID_BUTTON_SAVE_ESD = 10013;
const int ID_CHECKBOX_PLAYINGAME = 10014;
wxSizer *SoundEditDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
