//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: StallInfoDlg.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_StallInfoDlg_H__
#define __WDR_StallInfoDlg_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "StallInfoDlg_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT__CAN_STALL = 10000;
const int ID_TEXTCTRL__CAN_STALL = 10001;
const int ID_TEXT__TRADE_TAX = 10002;
const int ID_TEXTCTRL__TRADE_TAX = 10003;
const int ID_TEXT__POS_TAX = 10004;
const int ID_TEXTCTRL__POS_TAX = 10005;
const int ID_TEXT__EXTRAINFO = 10006;
const int ID_TEXTCTRL__EXTRAINFO = 10007;
const int ID_RADIOBUTTON_SET_STALL = 10008;
const int ID_RADIOBUTTON_DEL_STALL = 10009;
const int ID_RADIOBUTTON_VIEW_STALL = 10010;
const int ID_TEXTCTRL_STALL_INFO = 10011;
wxSizer *StallInfoDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
