//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: TerrainLightmapOption.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_TerrainLightmapOption_H__
#define __WDR_TerrainLightmapOption_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "TerrainLightmapOption_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int feID_PREVIEW = 10000;
const int feID_UPDATE_TERRAIN_LIGHTMAP = 10001;
extern wxSizer *mProgressSizer;
const int feID_UPDATE_TERRAIN_LIGHTMAP_PROGRESS = 10002;
const int feID_CANCEL_UPDATE_TERRAIN_LIGHTMAP = 10003;
const int feID_HIDE_TERRAIN_LIGHTMAP = 10004;
const int feID_SHOW_LOW_QUALITY_TERRAIN_LIGHTMAP = 10005;
const int feID_SHOW_HIGH_QUALITY_TERRAIN_LIGHTMAP = 10006;
wxSizer *TerrainLightmapOption( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

wxBitmap BitmapList( size_t index );

#endif

// End of generated file
