//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: TerrainSurfaceParameters.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_TerrainSurfaceParameters_H__
#define __WDR_TerrainSurfaceParameters_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "TerrainSurfaceParameters_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT = 10000;
const int ID_TEXTCTRL_AMBIENT = 10001;
const int ID_BUTTON_COLOUR_AMBIENT = 10002;
const int ID_TEXTCTRL_DIFFUSE = 10003;
const int ID_BUTTON_COLOUR_DIFFUSE = 10004;
const int ID_TEXTCTRL_SPECULAR = 10005;
const int ID_BUTTON_COLOUR_SPECULAR = 10006;
const int ID_TEXTCTRL_EMISSIVE = 10007;
const int ID_BUTTON_COLOUR_EMISSIVE = 10008;
const int ID_TEXTCTRL_SHININESS = 10009;
const int ID_BUTTON_OK = 10010;
const int ID_BUTTON_CANCEL = 10011;
wxSizer *TerrainSurfaceParams( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
