//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: WeaponSelector.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_WeaponSelector_H__
#define __WDR_WeaponSelector_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "WeaponSelector_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TREECTRL_WEAPON = 10000;
const int ID_LISTBOX_WEAPON_EFFECT = 10001;
const int ID_BUTTON_WEAPON_EFFECT_COLOUR = 10002;
const int ID_TEXTCTRL_COLOUR_TEXT = 10003;
const int ID_TEXT = 10004;
const int ID_TEXTCTRL_ALPHA = 10005;
wxSizer *WeaponSelector( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
